name: Weekly
on:
  push:
    branches:
    - master
  schedule:
    - cron: 0 0 * * 0

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: shards install
    - name: Run Test Suite
      run: |
        crystal tool format --check
        crystal spec
